version: '3.7'

services:
  web:
    image: lamp-container_apache-24
    restart: always
    depends_on:
      - php-fpm
      - db
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - .:/var/www/html:Z
      # - ./certificate:/usr/local/apache2/certificate:ro
  php-fpm:
    image: lamp-container_php-fpm-74
    restart: always
    volumes:
      - .:/var/www/html:Z
  db:
    image: lamp-container_mysql-55
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    ports:
      - "${PHPMYADMIN_PORT}:80"
    links:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
volumes:
  data:
    external:
      name: ${DB_VOLUME}
